#!/bin/sh

headvol() {
  amixer sget Headphone | grep 'Left:' | cut -d\  -f7 | tr -d '[%]'
}

mastervol() {
  pactl get-sink-volume 0 | grep -oP '\d+%' | head -n 1
}

micvol() {
  pactl get-source-volume 0 | grep -oP '\d+%' | head -n 1 | tr -d '%'
}

"$@"
